# Generated by Django 6.0.7 on 2026-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectator_reading', '0008_change_thumbnail_upload_to_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='removed_from_unread_date',
            field=models.DateField(blank=True, help_text='If this was disposed of unread, set the date it happened. Publication will be hidden everywhere, but will count as an unread publication for dates up to this.', null=True),
        ),
    ]
