# Generated by Django 6.0.7 on 2026-08-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectator_reading', '0009_publication_removed_from_unread_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='removed_from_unread_date',
        ),
        migrations.AddField(
            model_name='publication',
            name='date_removed',
            field=models.DateField(blank=True, help_text="When the Publication was first marked as 'Is removed'.", null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Removed Publications do not appear in lists and will not have a detail page, but they will count towards historical read and unread counts.', verbose_name='Is removed?'),
        ),
    ]
