# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_language_version = { python = "python3.14" }
exclude = """
(?x)^(
  dist/.*
  |spectator/core/static/spectator-core/css/bootstrap.*
)$
"""

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-added-large-files" }
]

[[repos]]
repo = "https://github.com/rbubley/mirrors-prettier"
rev = "v3.9.6"
hooks = [
  {
    id = "prettier",
    types_or = [
      "css",
      "javascript",
      "json"
    ]
  }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.1"
hooks = [
  {
    id = "ruff-check",
    args = ["--fix"]
  },
  { id = "ruff-format" }
]

[[repos]]
repo = "https://github.com/asottile/pyupgrade"
rev = "v3.21.2"
hooks = [
  {
    id = "pyupgrade",
    args = ["--py310-plus"]
  }
]
