# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_language_version = { python = "python3.14" }
exclude = """
(?x)^(
  dist/.*
  |spectator/core/static/spectator-core/css/bootstrap.*
)$
"""

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-added-large-files" }
]

[[repos]]
repo = "https://github.com/asottile/pyupgrade"
rev = "v3.21.2"
hooks = [
  {
    id = "pyupgrade",
    args = ["--py310-plus"]
  }
]

[[ repos ]]
repo = "https://github.com/adamchainz/django-upgrade"
rev = "1.31.1"
hooks = [
  {
    id =  "django-upgrade",
    args = ["--target-version", "5.2"]
  }
]


[[repos]]
repo = "local"
hooks = [
  {
    id = "local-biome-check",
    name = "biome check",
    entry = "npx biome check --write --files-ignore-unknown=true --no-errors-on-unmatched",
    language = "system",
    types = ["text"]
  }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.1"
hooks = [
  {
    id = "ruff-check",
    args = ["--fix"]
  },
  { id = "ruff-format" }
]
