# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='movie',
            field=models.ForeignKey(blank=True, help_text="Only used if event is of 'movie' kind.", null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Movie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='play',
            field=models.ForeignKey(blank=True, help_text="Only used if event is of 'play' kind.", null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Play'),
        ),
    ]
