# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170411_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='classical_works',
            field=models.ManyToManyField(blank=True, help_text="Only used if event is of 'Classical Concert' kind.", to='events.ClassicalWork'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dance_pieces',
            field=models.ManyToManyField(blank=True, help_text="Only used if event is of 'Dance' kind.", to='events.DancePiece'),
        ),
    ]
