# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170411_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='classical_works',
            new_name='classicalworks',
        ),
        migrations.AlterField(
            model_name='classicalwork',
            name='creators',
            field=models.ManyToManyField(related_name='classicalworks', through='events.ClassicalWorkRole', to='core.Creator'),
        ),
    ]
