# Generated by Django 2.0 on 2018-01-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectator_events', '0022_auto_20180129_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='cinema_treasures_id',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional. ID of a cinema at <a href="http://cinematreasures.org/">Cinema Treasures</a>.', null=True),
        ),
    ]
