# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time this item was created in the database.')),
                ('time_modified', models.DateTimeField(auto_now=True, help_text='The time this item was last saved to the database.')),
                ('name', models.CharField(help_text="e.g. 'Douglas Adams' or 'The Long Blondes'.", max_length=255)),
                ('sort_name', models.CharField(blank=True, help_text="e.g. 'Adams, Douglas' or 'Long Blondes, The'. If left blank, will be created automatically on save.", max_length=255)),
                ('kind', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=20)),
            ],
            options={
                'ordering': ('sort_name',),
            },
        ),
    ]
