# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0002_auto_20170303_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
