# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0002_auto_20170228_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='bookseries',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='book',
            name='kind',
            field=models.CharField(choices=[('book', 'Book'), ('periodical', 'Periodical')], default='book', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='url',
            field=models.URLField(blank=True, help_text="e.g. 'https://www.lrb.co.uk/'.", max_length=255, verbose_name='URL'),
        ),
    ]
