# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0003_remove_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='concert_title',
            new_name='title',
        ),
    ]
