# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0003_auto_20170228_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time this item was created in the database.')),
                ('time_modified', models.DateTimeField(auto_now=True, help_text='The time this item was last saved to the database.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_granularity', models.PositiveSmallIntegerField(choices=[(3, 'Y-m-d'), (4, 'Y-m'), (6, 'Y')], default=3)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_granularity', models.PositiveSmallIntegerField(choices=[(3, 'Y-m-d'), (4, 'Y-m'), (6, 'Y')], default=3)),
                ('is_finished', models.BooleanField(default=False, help_text='Did you finish the book?')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectator.Book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bookseries',
            options={'ordering': ('title',), 'verbose_name_plural': 'Book series'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('role_order', 'role_name')},
        ),
    ]
