# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0004_auto_20170304_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time this item was created in the database.')),
                ('time_modified', models.DateTimeField(auto_now=True, help_text='The time this item was last saved to the database.')),
                ('title', models.CharField(help_text="e.g. 'Aurora' or 'Vol. 39 No. 4, 16 February 2017'.", max_length=255)),
                ('kind', models.CharField(choices=[('book', 'Book'), ('periodical', 'Periodical')], default='book', max_length=20)),
                ('official_url', models.URLField(blank=True, help_text='Official URL for this book/issue.', max_length=255, verbose_name='Official URL')),
                ('isbn_gb', models.CharField(blank=True, help_text="e.g. '0356500489'.", max_length=20, verbose_name='UK ISBN')),
                ('isbn_us', models.CharField(blank=True, help_text="e.g. '0316098094'.", max_length=20, verbose_name='US ISBN')),
                ('notes_url', models.URLField(blank=True, help_text='URL of your notes/review.', max_length=255, verbose_name='Notes URL')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PublicationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time this item was created in the database.')),
                ('time_modified', models.DateTimeField(auto_now=True, help_text='The time this item was last saved to the database.')),
                ('role_name', models.CharField(blank=True, help_text="e.g. 'Headliner', 'Support', 'Editor', 'Illustrator', 'Director', etc. Optional.", max_length=50)),
                ('role_order', models.PositiveSmallIntegerField(default=1, help_text='The order in which the Creators will be listed.')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_roles', to='spectator.Creator')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='spectator.Publication')),
            ],
            options={
                'ordering': ('role_order', 'role_name'),
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='BookSeries',
            new_name='PublicationSeries',
        ),
        migrations.RemoveField(
            model_name='book',
            name='creators',
        ),
        migrations.RemoveField(
            model_name='book',
            name='series',
        ),
        migrations.RemoveField(
            model_name='bookrole',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookrole',
            name='creator',
        ),
        migrations.AlterModelOptions(
            name='publicationseries',
            options={'ordering': ('title',), 'verbose_name_plural': 'Publication series'},
        ),
        migrations.RemoveField(
            model_name='reading',
            name='book',
        ),
        migrations.AlterField(
            model_name='reading',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Did you finish the publication?'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookRole',
        ),
        migrations.AddField(
            model_name='publication',
            name='creators',
            field=models.ManyToManyField(related_name='publications', through='spectator.PublicationRole', to='spectator.Creator'),
        ),
        migrations.AddField(
            model_name='publication',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spectator.PublicationSeries'),
        ),
        migrations.AddField(
            model_name='reading',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spectator.Publication'),
            preserve_default=False,
        ),
    ]
