# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0005_auto_20170302_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='creators',
            field=models.ManyToManyField(related_name='books', through='spectator.BookRole', to='spectator.Creator'),
        ),
        migrations.AlterField(
            model_name='bookrole',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_roles', to='spectator.Book'),
        ),
        migrations.AlterField(
            model_name='bookrole',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_roles', to='spectator.Creator'),
        ),
        migrations.AlterField(
            model_name='bookrole',
            name='role_name',
            field=models.CharField(blank=True, help_text="e.g. 'Headliner', 'Support', 'Editor', 'Illustrator', 'Director', etc. Optional.", max_length=50),
        ),
    ]
