# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0005_auto_20170304_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'get_latest_by': 'end_date'},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='isbn_gb',
            new_name='isbn_uk',
        ),
    ]
