# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0008_auto_20170302_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertrole',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='spectator.Concert'),
        ),
    ]
