# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0009_auto_20170302_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrole',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='spectator.Book'),
        ),
    ]
