# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 19:15
from __future__ import unicode_literals

from django.db import migrations
import spectator.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0009_auto_20170314_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='name_individual_sort',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='name_individual_sort_display',
        ),
        migrations.AlterField(
            model_name='creator',
            name='name_sort',
            field=spectator.fields.NaturalSortField('name', db_index=True, default='', editable=False, help_text="Best for sorting groups. e.g. 'long blondes, the' or 'adams, douglas'.", max_length=255),
        ),
    ]
