# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:17
from __future__ import unicode_literals

from django.db import migrations
import spectator.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0010_auto_20170314_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_sort',
            field=spectator.fields.NaturalSortField('title', db_index=True, default='', editable=False, help_text="e.g. 'haine, la' or 'unbelievable truth, the'.", max_length=255),
        ),
        migrations.AddField(
            model_name='play',
            name='title_sort',
            field=spectator.fields.NaturalSortField('title', db_index=True, default='', editable=False, help_text="e.g. 'big play, a' or 'biggest play, the'.", max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='name_sort',
            field=spectator.fields.NaturalSortField('name', db_index=True, default='', editable=False, help_text="e.g. 'venue, a' or 'biggest venue, the'.", max_length=255),
        ),
    ]
