# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:29
from __future__ import unicode_literals

from django.db import migrations
import spectator.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0011_auto_20170320_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title_sort',)},
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ('title_sort',)},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name_sort']},
        ),
        migrations.AddField(
            model_name='concert',
            name='title_sort',
            field=spectator.fields.NaturalSortField('__str__', db_index=True, default='', editable=False, help_text="e.g. 'reading festival, the' or 'drifters, the'.", max_length=255),
        ),
    ]
