# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:30
from __future__ import unicode_literals

from django.db import migrations
import spectator.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0012_auto_20170320_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='title_sort',
            field=spectator.fields.NaturalSortField('title_to_sort', db_index=True, default='', editable=False, help_text="e.g. 'reading festival, the' or 'drifters, the'.", max_length=255),
        ),
    ]
