# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0012_auto_20170302_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playproductionrole',
            name='play',
        ),
    ]
