# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectator', '0013_auto_20170320_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ('title_sort',)},
        ),
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='country',
            field=models.CharField(blank=True, help_text="The ISO 3166-1 alpha-2 code, e.g. 'GB' or 'FR'", max_length=2),
        ),
    ]
